### ISSUE TITLE
[Bug]: cant claim the !refer 1 week and 1month rewards

### ISSUE THREAD

**Issue by Vrevil0** [Quebec-Games/issues#23] opened 2022-10-13 20:11 UTC
### Which server is this bug report for?

Murderer's Arena

### Issue description

When i try to claim the 1week or/and the 1month reward in !refer, it tells me that the Discord Application isnt open, open it to verify. Yes i am a member of the discord for over a month and i am already verifyed. Help

### Expected Behavior

Well i expected someone could fix it without reporting but i couldnt get anyone that is able to do so.

### Current Behavior

None really

### Screenshots/Videos

![20221013220936_1](https://user-images.githubusercontent.com/115741568/195699670-7cd1124e-c5ef-4424-bcb4-ac91489cd636.jpg)

**Comment by Ecorte** [comment] 2022-10-13 20:35
Dupe of #11

**Closed by Ecorte** 2022-10-13 20:35 UTC
Labels: bug
